inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
  DisplayStyleGuide: true
  DisplayCopNames: true
Rails:
  Enabled: true
# https://github.com/bbatsov/rubocop/issues/1633
Rails/Output:
  Exclude:
    - 'lib/**/*'
