require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
  DisplayStyleGuide: true
  DisplayCopNames: true
# https://github.com/bbatsov/rubocop/issues/1633
