language: ruby
rvm:
- 2.1.9
- 2.3.1
cache: bundler
bundler_args: --without production
sudo: false
script:
  - bundle exec rspec
  - bundle exec rubocop
addons:
  code_climate:
    repo_token:
      secure: m8cpu/I6W+mlQ9x9qxIZqsCJcrM/CyxwnvlUnSeNyCw2fPdGbj4P0waXVfG13E/xl/P5d+Sb3cz5Pb0e5csDRkO1Q0u+wXHZgTlUldQljleGjox2qhTLdDC+vM7osyTDHxZCbo+nFrimJL1HMwLXwoQT7uOhC6ynltvy5/RHvMc=
notifications:
  slack:
    secure: g4J7x0H2sPORDxwrXSVc9a7Jh4V3HRePZ0XV0h4CQpToRu/PQlglcqfNtZq94hWaQiM1aztDvb6M+bAj03/7kpE1aGk7bIT9AZTvgjHEqEhhw9td4KhcBKKJ1NWck1efkRNgHVGL+uNaP8jFyG2tDk8iHTfe3ljXaKnS2sZhK1Y=
